# Generated by Django 4.1.3 on 2022-12-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_permission_permission_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
