# Generated by Django 4.1.3 on 2022-12-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_permission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': ' Cities'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': ' Registrations'},
        ),
    ]
